language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
  global:
    - PACKAGE=key-parsers
    - DISTRO=debian-stable
  matrix:
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.08
    - OCAML_VERSION=4.09
    - OCAML_VERSION=4.10