language: c
os: linux
dist: xenial
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash .travis-opam.sh
env:
  global:
    - PACKAGE=key-parsers
  matrix:
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.08
    - OCAML_VERSION=4.09
    - OCAML_VERSION=4.10
    - OCAML_VERSION=4.11
